name: Update Burn and Donations JSON

on:
  schedule:
    - cron: "*/10000000 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-json-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Burn Script
        run: node scripts/burn.js

      - name: Run Donation Script
        run: node scripts/donation.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add burn.json donations.json
          git commit -m "Update burn.json and donations.json [Automated]" || echo "No changes to commit"
          git push
